# Generated by Django 4.2.4 on 2023-10-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_paciente_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='castracao',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(choices=[('FELINO', 'Felino'), ('CANINO', 'Canino')], default='', max_length=100),
        ),
    ]
