# Generated by Django 4.2.4 on 2023-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>/%Y/%m/%d'),
        ),
    ]
