# Generated by Django 4.2.4 on 2023-10-20 13:29

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateTimeField(default=index.models.Paciente.data_atual_sem_hora),
        ),
    ]
