# Generated by Django 4.2.4 on 2023-10-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tutor', to='index.tutor'),
        ),
    ]
