# Generated by Django 4.2.4 on 2023-11-13 15:41

import apps.index.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('endereco', models.TextField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RacaCanino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RacaFelino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('nascimento', models.DateField(default=apps.index.models.Paciente.data_atual_sem_hora)),
                ('peso', models.CharField(max_length=100)),
                ('castracao', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to=apps.index.models.get_upload_path)),
                ('raca_canino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_canino_paciente', to='index.racacanino')),
                ('raca_felino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_felino_paciente', to='index.racafelino')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='index.tutor')),
            ],
        ),
    ]
