# Generated by Django 4.2.4 on 2023-11-13 16:04

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(blank=True, default=apps.index.models.Paciente.data_atual_sem_hora, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
