# Generated by Django 4.2.4 on 2023-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='categoria',
            field=models.CharField(choices=[('FELINO', 'Felino'), ('CANINO', 'Canino')], default='', max_length=100),
        ),
    ]
