# Generated by Django 4.2.4 on 2023-11-13 16:04

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_clinica_email_alter_clinica_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(default=apps.index.models.Paciente.data_atual_sem_hora),
        ),
    ]
