# Generated by Django 4.2.4 on 2023-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_paciente_categoria_alter_paciente_castracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='castracao',
            field=models.BooleanField(default=False),
        ),
    ]
