# Generated by Django 4.2.4 on 2023-11-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('email_tutor', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('email_extra', models.CharField(max_length=100)),
                ('telefone_extra', models.CharField(max_length=100)),
                ('suspeita', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('laudo', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to='index.clinica')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='index.paciente')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='index.tutor')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='index.veterinario')),
            ],
        ),
    ]
