# Generated by Django 4.2.4 on 2023-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_clinica_data_criacao_paciente_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
