# Generated by Django 4.2.4 on 2023-11-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_paciente_laudo_nome_alter_laudo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='nome',
        ),
        migrations.AddField(
            model_name='laudo',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='index.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Fêmea')], default='Macho', max_length=5),
        ),
    ]
