# Generated by Django 4.2.4 on 2023-11-14 17:40

import apps.index.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_laudo_nome_laudo_paciente_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(default=apps.index.models.Paciente.idade),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca_canino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_canino_paciente', to='index.racacanino'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca_felino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_felino_paciente', to='index.racafelino'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], default='Macho', max_length=5),
        ),
    ]
