# Generated by Django 4.2.4 on 2023-11-14 17:48

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_paciente_nascimento_alter_paciente_raca_canino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(default=apps.index.models.Paciente.data_atual_sem_hora),
        ),
    ]
