# Generated by Django 4.2.4 on 2023-11-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='index.paciente'),
        ),
    ]
