# Generated by Django 4.2.4 on 2023-10-20 13:20

import datetime
from django.db import migrations, models
import apps.index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to=apps.index.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
