# Generated by Django 4.2.4 on 2023-10-20 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_paciente_foto_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateTimeField(default=datetime.date(2023, 10, 20)),
        ),
    ]
