# Generated by Django 4.2.4 on 2023-11-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_laudo_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='nome',
            new_name='nome_tutor',
        ),
    ]
