# Generated by Django 4.2.4 on 2023-11-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_nome_tutor_nome_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laudo',
            old_name='tutor',
            new_name='nome_tutor',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tutor',
            new_name='nome_tutor',
        ),
    ]
