# Generated by Django 4.2.4 on 2023-11-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_rename_tutor_laudo_nome_tutor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laudo',
            old_name='paciente',
            new_name='nome_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nome',
            new_name='nome_paciente',
        ),
    ]
