# Generated by Django 4.2.4 on 2023-11-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_rename_nome_paciente_laudo_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laudo',
            old_name='paciente',
            new_name='nome_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nome',
            new_name='nome_paciente',
        ),
    ]
