# Generated by Django 4.2.4 on 2023-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_paciente_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
