# Generated by Django 4.2.4 on 2023-11-06 16:02

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_paciente_foto_alter_paciente_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to=apps.index.models.get_upload_path),
        ),
    ]
