# Generated by Django 4.2.4 on 2023-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.CharField(max_length=100),
        ),
    ]
