# Generated by Django 4.2.4 on 2023-11-17 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_laudo_laudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='laudo',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
