# Generated by Django 4.2.4 on 2023-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_paciente_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacaFelino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(default='Felino'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(choices=[('PCB', 'PCB'), ('PERSA', 'Persa')], max_length=150),
        ),
    ]
