# Generated by Django 4.2.4 on 2023-11-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_racafelino_alter_paciente_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RacaFelino', to='index.racafelino'),
        ),
    ]
