# Generated by Django 4.2.4 on 2023-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_paciente_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacaCaninos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100)),
            ],
        ),
    ]
