# Generated by Django 4.2.4 on 2023-11-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_racacaninos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RacaCaninos',
            new_name='RacaCanino',
        ),
    ]
