# Generated by Django 4.2.4 on 2023-11-20 17:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_frases'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='tipo_laudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_laudo', to='index.laudospadrao'),
        ),
        migrations.AlterField(
            model_name='frases',
            name='texto',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='laudospadrao',
            name='laudo',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
