# Generated by Django 4.2.4 on 2023-11-09 11:48

import apps.index.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_rename_racacaninos_racacanino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='index.tutor'),
        ),
        migrations.CreateModel(
            name='PacienteCanino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(default='Canino')),
                ('nascimento', models.DateField(default=apps.index.models.PacienteCanino.data_atual_sem_hora)),
                ('peso', models.CharField(max_length=100)),
                ('castracao', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to=apps.index.models.get_upload_path)),
                ('raca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RacaCanino', to='index.racacanino')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_caninos', to='index.tutor')),
            ],
        ),
    ]
