# Generated by Django 4.2.4 on 2023-11-20 17:58

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_laudo_tipo_laudo_alter_frases_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to=apps.index.models.get_upload_path),
        ),
    ]
