# Generated by Django 4.2.4 on 2023-11-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_alter_paciente_tutor_pacientecanino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='raca',
        ),
        migrations.AddField(
            model_name='paciente',
            name='raca_canino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_canino_paciente', to='index.racacanino'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='raca_felino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raca_felino_paciente', to='index.racafelino'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(max_length=100),
        ),
    ]
