# Generated by Django 4.2.4 on 2023-11-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_laudo_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='imagens',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
