# Generated by Django 4.2.4 on 2023-11-21 13:22

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_remove_laudo_imagens_alter_paciente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='frases',
            name='palavra_chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frases',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.index.models.get_upload_path),
        ),
    ]
