# Generated by Django 4.2.4 on 2023-11-21 14:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_frases_palavra_chave_frases_tipo_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frases',
            name='palavra_chave',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='frases',
            name='tipo',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
