# Generated by Django 4.2.4 on 2023-11-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_frases_palavra_chave_alter_frases_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='idade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='peso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
