# Generated by Django 4.2.4 on 2023-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_laudo_email_alter_laudo_idade_alter_laudo_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
