# Generated by Django 4.2.4 on 2023-11-22 13:13

import apps.index.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_alter_paciente_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.index.models.get_upload_path, verbose_name='Arquivos')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudo_imagem', to='index.laudo')),
            ],
        ),
    ]
