# Generated by Django 4.2.4 on 2023-11-22 19:20

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_alter_laudoimagem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudoimagem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.index.models.get_upload_path, verbose_name='Arquivos'),
        ),
    ]
