# Generated by Django 4.2.4 on 2023-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_alter_laudoimagem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data',
            field=models.DateField(),
        ),
    ]
