# Generated by Django 4.2.4 on 2023-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_alter_laudo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('proxima_execucao', models.DateTimeField()),
            ],
        ),
    ]
