# Generated by Django 4.2.4 on 2023-11-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_tarefaagendada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarefaAgendada',
        ),
    ]
