# Generated by Django 4.2.4 on 2023-12-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_delete_tarefaagendada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto',
        ),
    ]
