# Generated by Django 4.2.4 on 2023-12-15 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_remove_paciente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 1, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
