# Generated by Django 4.2.4 on 2023-12-20 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_laudo_hora_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 20, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
