# Generated by Django 4.2.4 on 2023-12-27 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_alter_laudo_data_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='tipo_laudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_laudo', to='index.laudospadrao'),
        ),
    ]
