# Generated by Django 4.2.4 on 2024-01-16 12:22

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_alter_laudo_hora_envio_alter_laudo_tipo_laudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 16, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
