# Generated by Django 4.2.4 on 2024-01-17 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_laudo_preco_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
