# Generated by Django 4.2.4 on 2024-01-22 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinica',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='racacanino',
            options={'ordering': ['raca']},
        ),
        migrations.AlterModelOptions(
            name='racafelino',
            options={'ordering': ['raca']},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='laudo',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 22, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
