# Generated by Django 4.2.4 on 2024-01-29 13:07

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_paciente_observacao_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('gel_usg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_10ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_5ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_3ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('agulha_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('cateter_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('cateter_rosa', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('gaze_n_esteril', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('pano_de_campo', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('essencia_spray', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('papel_quadrado', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('desinfetante_herbal', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('prope', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_60ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('scal_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='nota_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 29, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
