# Generated by Django 4.2.4 on 2024-01-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_inventario_laudo_data_pagamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='nota_fiscal',
        ),
    ]
