# Generated by Django 4.2.4 on 2024-01-29 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0048_delete_inventario_remove_laudo_data_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('gel_usg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_10ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_5ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_3ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('agulha_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('cateter_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('cateter_rosa', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('gaze_n_esteril', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('pano_de_campo', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('essencia_spray', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('papel_quadrado', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('desinfetante_herbal', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('prope', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('seringa_60ml', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
                ('scal_azul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8)),
            ],
        ),
    ]
