# Generated by Django 4.2.4 on 2024-01-29 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0049_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='data_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='nota_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laudo',
            name='preco_real',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
