# Generated by Django 4.2.4 on 2024-01-30 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0051_alter_laudo_preco_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='laudo_pronto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 30, 1, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
