# Generated by Django 4.2.4 on 2024-01-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0053_formadepagamento_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudos_forma_pagamento', to='index.FormaDePagamento'),
        ),
    ]
