# Generated by Django 4.2.4 on 2024-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_alter_laudo_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='observacao_pagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
