# Generated by Django 4.2.4 on 2024-07-19 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0055_laudo_observacao_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='mensagem_whatsapp',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 19, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
