# Generated by Django 4.2.4 on 2024-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0056_laudo_mensagem_whatsapp_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='mensagem_whatsapp',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
