# Generated by Django 4.2.4 on 2024-08-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0057_alter_laudo_mensagem_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='enviar_agora',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
