# Generated by Django 4.2.4 on 2024-10-23 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0058_laudo_enviar_agora_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 23, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
