# Generated by Django 4.2.4 on 2024-11-14 11:31

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0059_paciente_obito_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='luva',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
