# Generated by Django 4.2.4 on 2024-12-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0060_inventario_luva_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='plano',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 16, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
