# Generated by Django 4.2.4 on 2024-12-31 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0061_paciente_plano_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='acompanhamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='exame_do_acompanhamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 31, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
