# Generated by Django 4.2.4 on 2024-12-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0062_paciente_acompanhamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='exame_do_acompanhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_com_este_exame', to='index.laudospadrao', verbose_name='Exame do Acompanhamento'),
        ),
    ]
