# Generated by Django 4.2.4 on 2025-01-03 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0063_alter_paciente_exame_do_acompanhamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='acompanhamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exame_do_acompanhamento',
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 3, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='AcompanhamentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acompanhamento', models.DateField(verbose_name='Data do Acompanhamento')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='index.laudospadrao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='index.paciente')),
            ],
        ),
    ]
