# Generated by Django 4.2.4 on 2025-01-06 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0065_paciente_acompanhamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='acompanhamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exame_do_acompanhamento',
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 6, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('exame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos', to='index.laudospadrao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='index.paciente')),
            ],
        ),
    ]
