# Generated by Django 4.2.4 on 2025-01-07 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0066_remove_paciente_acompanhamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 7, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
