# Generated by Django 4.2.4 on 2025-01-24 19:06

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0067_alter_laudo_hora_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True)),
                ('recorrencia', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 24, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
