# Generated by Django 4.2.4 on 2025-01-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0069_tipodespesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodespesa',
            old_name='nome',
            new_name='nome_despesa',
        ),
    ]
