# Generated by Django 4.2.4 on 2025-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0072_remove_despesa_recorrencia_despesa_recorrencia_atual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['data']},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='recorrencia_atual',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='recorrencia_total',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
