# Generated by Django 4.2.4 on 2025-02-07 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0073_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='hora_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 7, 23, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
